
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LEFTBRACKET = 44;
  public static final int UMINUS = 52;
  public static final int PERIOD = 41;
  public static final int RIGHTBRACKET = 45;
  public static final int RIGHTPAREN = 43;
  public static final int DOUBLE = 5;
  public static final int NOTEQUAL = 34;
  public static final int GREATER = 31;
  public static final int INTERFACE = 13;
  public static final int INT = 12;
  public static final int PRINTLN = 17;
  public static final int LESS = 29;
  public static final int FOR = 9;
  public static final int MINUS = 25;
  public static final int LEFTPAREN = 42;
  public static final int SEMICOLON = 39;
  public static final int NOT = 37;
  public static final int AND = 35;
  public static final int LESSEQUAL = 30;
  public static final int OR = 36;
  public static final int COMMA = 40;
  public static final int DOUBLECONSTANT = 49;
  public static final int CLASS = 4;
  public static final int NEWARRAY = 15;
  public static final int PLUS = 24;
  public static final int IF = 10;
  public static final int THIS = 21;
  public static final int ID = 51;
  public static final int INTCONSTANT = 48;
  public static final int EOF = 0;
  public static final int BOOLEAN = 2;
  public static final int RETURN = 19;
  public static final int EQUAL = 33;
  public static final int STRINGCONSTANT = 50;
  public static final int NEW = 14;
  public static final int error = 1;
  public static final int NULL = 16;
  public static final int MOD = 28;
  public static final int BREAK = 3;
  public static final int VOID = 22;
  public static final int READLN = 18;
  public static final int ASSIGNOP = 38;
  public static final int GREATEREQUAL = 32;
  public static final int RIGHTBRACE = 47;
  public static final int ELSE = 6;
  public static final int WHILE = 23;
  public static final int BOOLEANCONSTANT = 8;
  public static final int LEFTBRACE = 46;
  public static final int EXTENDS = 7;
  public static final int STRING = 20;
  public static final int DIVISION = 27;
  public static final int IMPLEMENTS = 11;
  public static final int MULTIPLICATION = 26;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "BOOLEAN",
  "BREAK",
  "CLASS",
  "DOUBLE",
  "ELSE",
  "EXTENDS",
  "BOOLEANCONSTANT",
  "FOR",
  "IF",
  "IMPLEMENTS",
  "INT",
  "INTERFACE",
  "NEW",
  "NEWARRAY",
  "NULL",
  "PRINTLN",
  "READLN",
  "RETURN",
  "STRING",
  "THIS",
  "VOID",
  "WHILE",
  "PLUS",
  "MINUS",
  "MULTIPLICATION",
  "DIVISION",
  "MOD",
  "LESS",
  "LESSEQUAL",
  "GREATER",
  "GREATEREQUAL",
  "EQUAL",
  "NOTEQUAL",
  "AND",
  "OR",
  "NOT",
  "ASSIGNOP",
  "SEMICOLON",
  "COMMA",
  "PERIOD",
  "LEFTPAREN",
  "RIGHTPAREN",
  "LEFTBRACKET",
  "RIGHTBRACKET",
  "LEFTBRACE",
  "RIGHTBRACE",
  "INTCONSTANT",
  "DOUBLECONSTANT",
  "STRINGCONSTANT",
  "ID",
  "UMINUS"
  };
}

